function folderName = makePSDFolderName(options)
if options.chunks == 0
    folderName = sprintf('%s_wdw%ss_over%.0f_out%s_noChk', options.method,...
        replace(sprintf('%g',options.window/options.SR),'.','-'),...
        100*options.overlap/options.window, options.output);
else
    folderName = sprintf('%s_wdw%ss_over%.0f_out%s_%ssChk', options.method,...
        replace(sprintf('%g',options.window/options.SR),'.','-'),...
        100*options.overlap/options.window, options.output,...
        replace(sprintf('%g',options.chunks),'.','-'));
end
end